---
Standards:
  -
    Title: Introduction
    Description: Introduction
    UID: 7c1d840f-06c8-4dc5-a10a-8fdf61f99c8f
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c831a8e5-20d5-42df-883e-bb0f4deb0e1c
        Path: /00-intro/intro-live.md
      -
        Type: Lesson
        UID: 29924803-96e7-4460-be80-5ca78480bdee
        Path: /00-intro/intro-async.md
  -
    Title: Submit Study Plan
    Description: Create and submit your Unit 4 Study Plan
    UID: 9a0ddc53-aa81-4880-8fa1-b243fbff2c15
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: b5b601ec-4795-442d-b91e-81c046df35f5
        Path: /00-study-plan/study-plan.checkpoint.md
  -
    Title: Algorithmic Approaches
    Description: Introduction to Algorithms, Analysis of Algorithms, Recursion Review, Divide and Conquer, ...
    UID: ccdccab2-b7f3-42d8-977d-955a58ce9d05
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a76dfc02-3b54-459c-bf72-66a072b26119
        Path: /01-algorithms/01-algorithms.md
      -
        Type: Lesson
        UID: 7efe05b0-1021-403b-8f13-553beec28cfe
        Path: /01-algorithms/02-algorithm-analysis.md
      -
        Type: Lesson
        UID: 70754423-d4bc-4fc2-8bfc-a6673574d8f4
        Path: /01-algorithms/03-recursion.md
      -
        Type: Lesson
        UID: 1609881b-773a-41e3-aee7-c23c66e20d29
        Path: /01-algorithms/04-algorithms-divide-conquer.md
      -
        Type: Lesson
        UID: d623f94b-71bc-414b-b138-a4b0264aefcf
        Path: /01-algorithms/05-sliding-window.md
      -
        Type: Lesson
        UID: 54496b4c-78bc-46ba-92b4-53ccee97e41f
        Path: /01-algorithms/06-algorithms-dynamic-programming.md
      -
        Type: Lesson
        UID: e7ac6f0e-1186-4060-8be5-29e46b2fe352
        Path: /01-algorithms/07-algorithms-supplemental-resources.md
      -
        Type: Lesson
        UID: 0f52cf8b-80de-4c9f-9b98-53047d37b0a2
        Path: /01-algorithms/08-algorithms-activity-live.md
      -
        Type: Lesson
        UID: 54a01a9a-0f24-48f7-97ab-9d55f4da06dc
        Path: /01-algorithms/08-algorithms-activity-async.md
      -
        Type: Lesson
        UID: 3e63e944-118b-4904-96d7-ce35e0734f98
        Path: /01-algorithms/09-algorithms-class-discussion.md
  -
  
    Title: Linked Lists
    Description: Linked Lists, Object Oriented Design of a Linked List, Linked List Methods, Applications of Linked Lists, Supplemental Concepts
    UID: 8e6f54bf-41e8-41d6-9a03-dca103bf15ed
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: c498e182
        Path: /02-linked-lists/linked-lists.instructor.md
      -
        Type: Instructor
        UID: ac3b6860-51fd-4d90-8a68-99875639af1d
        Path: /02-linked-lists/class-lesson.instructor.md
      -
        Type: Lesson
        UID: 99474aeb-183e-4f01-990b-0a689c022c30
        Path: /02-linked-lists/01-linked-lists.md
      -
        Type: Lesson
        UID: 1622f195-c5bf-4c9e-ab13-f245ed963cc4
        Path: /02-linked-lists/02-linked-lists-oop.md
      -
        Type: Lesson
        UID: 0c78e210-d831-41dd-956b-973aa151d904
        Path: /02-linked-lists/03-linked-lists-implementation.md
      -
        Type: Lesson
        UID: 444cda30-ac77-4abd-858b-9db81b6f601d
        Path: /02-linked-lists/04-linked-lists-stacks-queues.md
      -
        Type: Lesson
        UID: 0d3a9473-199c-430d-bc55-43fc09fd50ff
        Path: /02-linked-lists/05-linked-lists-supplemental-concepts.md
      -
        Type: Lesson
        UID: 19b1fbf3-60b6-4a60-895c-7de1b9afe923
        Path: /02-linked-lists/06-linked-list-activity-live.md
      -
        Type: Lesson
        UID: 60969afa-ab45-49b5-ad78-b2f25c1274ea
        Path: /02-linked-lists/06-linked-list-activity-async.md
      -
        Type: Lesson
        UID: 2c227840-f6ff-4022-a16f-25a3eabf1d41
        Path: /02-linked-lists/07-linked-lists-class-discussions.md
  -
    Title: Binary Search Trees
    Description: Binary Search Trees, Balancing Trees, Serializing with Tree Traversal, Resources
    UID: fc8d8eae-2456-4b22-9213-127d6e83dd5e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: e153ec41-477e-43fb-bf6d-0173e24aec85
        Path: /03-Binary-Search-Trees/bst.instructor.md
      -
        Type: Lesson
        UID: 05732e84-1354-4349-8c71-173460093f9b
        Path: /03-Binary-Search-Trees/01-Binary-Search-Trees.md
      -
        Type: Lesson
        UID: c7d8f1dc-2d74-4892-a2ab-69fbd3418ee3
        Path: /03-Binary-Search-Trees/02-Binary-Search-Trees-Big-O.md
      -
        Type: Lesson
        UID: 80747284-c3bb-4753-8c1b-9eb0bb834687
        Path: /03-Binary-Search-Trees/03-Binary-Search-Trees-Traversal.md
      -
        Type: Lesson
        UID: 1f189042-63dd-4075-9de9-4ca60a3fa5aa
        Path: /03-Binary-Search-Trees/04-Binary-Search-Trees-Resources.md
      -
        Type: Lesson
        UID: 06dea201-6230-4967-b98f-2403ab11479a
        Path: /03-Binary-Search-Trees/05-Binary-Search-Trees-Activity-Live.md
      -
        Type: Lesson
        UID: 6bed9f6e-2c70-4ed3-b0c7-e761db525eee
        Path: /03-Binary-Search-Trees/05-Binary-Search-Trees-Activity-Async.md
      -
        Type: Lesson
        UID: f5fc7ed6-5231-4667-a64f-aee2ff4d6652
        Path: /03-Binary-Search-Trees/06-Binary-Search-Trees-Class-Discussions.md
  -
    Title: Graphs Pt. 1
    Description: Graphs, Representing Graphs, Graphs Algorithms - Breadth First Search, Graph Algorithms - Depth First Search, Resources
    UID: b0d74464-2678-44a8-a4ff-dc74350e7114
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 43ec38b5-3ce1-4882-b709-ca99d4b702c1
        Path: /04-graphs/01-graphs.md
      -
        Type: Lesson
        UID: 97afeb52-3626-4cec-95ca-e19171f6d3b8
        Path: /04-graphs/02-representing-graphs.md
      -
        Type: Lesson
        UID: 2c83a545-e3fb-4f7f-bd88-3493883e9fa0
        Path: /04-graphs/03-bfs.md
      -
        Type: Lesson
        UID: e18e38d1-7995-4e57-80e8-ea3f276741d0
        Path: /04-graphs/04-dfs.md
      -
        Type: Lesson
        UID: 99cede61-070b-4d37-904c-ea12aba787b5
        Path: /04-graphs/05-application.md
      -
        Type: Lesson
        UID: b7554bcb-53aa-4db8-b447-1c2e4145b1e0
        Path: /04-graphs/06-graphs-resources.md
      -
        Type: Lesson
        UID: 96fcef62-30b0-4be7-8a63-c4002a53b0e2
        Path: /04-graphs/07-graphs-activity.md
      -
        Type: Lesson
        UID: f5a53e36-300b-4568-9301-08963aad977f
        Path: /04-graphs/08-graphs-class-discussions.md
  -
    Title: Graphs Pt. 2
    Description: Graph Data Structures & Algorithms - Dijkstra's
    UID: 37e5c085-d3c7-4905-867e-90bd70a14ceb
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a1c9e6cf-0bb8-4d02-bd5e-bda148023dd9
        Path: /05-dijkstras/01-graph-representations-review.md
      -
        Type: Lesson
        UID: 401e07cc-abf5-46a4-880f-b61ced1dc235
        Path: /05-dijkstras/02-traversal-review.md
      -
        Type: Lesson
        UID: a0b4d6af-65fb-4d82-bd37-0f952f9c3b92
        Path: /05-dijkstras/03-dijkstra.md
      -
        Type: Lesson
        UID: b11a0602-959e-42a2-9670-e7d126e9d98c
        Path: /05-dijkstras/04-dijkstras-activity.md
      -
        Type: Lesson
        UID: 99db9e58-5ab4-489c-a240-9c67195c7f82
        Path: /05-dijkstras/05-dijkstras-class-discussions.md
      -
        Type: Lesson
        UID: 720fe4c8-78f4-11ee-b962-0242ac120002
        Path: /05-dijkstras/06-dijkstras-vs-negative-graphs.md